// <auto-generated />
using System;
using EncontreItens.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EncontreItens.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20220409165520_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiAchadosAccurate.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaId");

                    b.ToTable("TbCategoria");
                });

            modelBuilder.Entity("ApiAchadosAccurate.Models.HistoricoAchados", b =>
                {
                    b.Property<int>("HistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoricoId"), 1L, 1);

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("ProdutoHistoricoID")
                        .HasColumnType("int");

                    b.Property<int>("StatusProdutoHistoricoStatusProdutoId")
                        .HasColumnType("int");

                    b.HasKey("HistoricoId");

                    b.HasIndex("ProdutoHistoricoID");

                    b.HasIndex("StatusProdutoHistoricoStatusProdutoId");

                    b.ToTable("TbHistorico");
                });

            modelBuilder.Entity("ApiAchadosAccurate.Models.Produto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoObjeto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("DocumentoPessoa")
                        .HasColumnType("bigint");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("Telefone")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CategoriaId");

                    b.ToTable("TbProduto");
                });

            modelBuilder.Entity("ApiAchadosAccurate.Models.StatusProduto", b =>
                {
                    b.Property<int>("StatusProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusProdutoId"), 1L, 1);

                    b.Property<string>("DescricaoTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusProdutoId");

                    b.ToTable("TbStatus");
                });

            modelBuilder.Entity("ApiAchadosAccurate.Models.HistoricoAchados", b =>
                {
                    b.HasOne("ApiAchadosAccurate.Models.Produto", "ProdutoHistorico")
                        .WithMany()
                        .HasForeignKey("ProdutoHistoricoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiAchadosAccurate.Models.StatusProduto", "StatusProdutoHistorico")
                        .WithMany()
                        .HasForeignKey("StatusProdutoHistoricoStatusProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProdutoHistorico");

                    b.Navigation("StatusProdutoHistorico");
                });

            modelBuilder.Entity("ApiAchadosAccurate.Models.Produto", b =>
                {
                    b.HasOne("ApiAchadosAccurate.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
